language: python
python:
  - 3.10

os: linux

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pytest numba
  - source activate test-environment
  - pip install python-coveralls pytest-cov

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.10 ]];
    then py.test -vv tests.py --cov .;
    else py.test -vv tests.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.10 ]];
    then coveralls;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.10 ]];
    then codecov;
    fi

notifications:
  email: false
